### ISSUE TITLE
部署的实际文件没有_images文件夹

### ISSUE THREAD

**Issue by Geniucker** [cyc-987/cyc-987.github.io#1]
rt，你换个文件夹名字试试，说不定是下划线的问题
![image](https://user-images.githubusercontent.com/61449208/234444219-2c6b0250-cbeb-4972-96d3-378a3dbb203c.png)

**Comment by cyc-987** [comment]
我去研究一下

**Comment by cyc-987** [comment]
确实是下划线的问题😂
